Update format_yaml.yml

diff --git a/.github/workflows/format_yaml.yml b/.github/workflows/format_yaml.yml
--- a/.github/workflows/format_yaml.yml
+++ b/.github/workflows/format_yaml.yml
@@ -23,7 +23,10 @@ jobs:
         run: npm install -g prettier
 
       - name: Auto-format YAML files
-        run: prettier --write '**/*.yaml' '**/*.yml'
+        run: |
+          for file in $(find . -type f \( -name '*.yml' -o -name '*.yaml' \)); do
+            prettier --write "$file" || echo "Error formatting $file, continuing..."
+          done
 
       - name: Check for changes
         run: |
